#!/usr/bin/env python3 -u

import sys
import re
import subprocess

if not len(sys.argv) > 1:
    print("Specify regex(s) to inform on their appearance in stdin")
    exit(-1)

regexs = {}
for r in sys.argv[1:]:
    regexs[r] = re.compile(r)

ansi_escape_re = re.compile(r'\x1b[^m]*m')
def trim_ansi_esc(text):
    return ansi_escape_re.sub('', text)

quotes_re = re.compile(r'"')
def safe_text(text):
    return quotes_re.sub('\\\"', line)

try:
    for line in sys.stdin:
        line = line.rstrip()
        print(line)
        no_ansi_escapes = trim_ansi_esc(line)
        for k in regexs:
            if len(regexs[k].findall(no_ansi_escapes)) > 0:
                safe_line = trim_ansi_esc(safe_text(no_ansi_escapes))
                osascript = """display notification "{}" with title "{}" subtitle "{}" """.format(safe_line, "Informing that", "")
                subprocess.run(["/usr/bin/osascript", "-e", osascript])
except KeyboardInterrupt:
    sys.exit(0)
